const names = [
    'Miguel',
    'Sophia',
    'Davi',
    'Alice',
    'Arthur',
    'Julia',
    'Pedro',
    'Isabella',
    'Gabriel',
    'Manuela',
    'Bernardo',
    'Laura',
    'Lucas',
    'Luiza',
    'Matheus',
    'Valentina',
    'Rafael',
    'Giovanna',
    'Heitor',
    'Maria',
    'Eduarda',
    'Enzo',
    'Helena',
    'Guilherme',
    'Beatriz',
    'Nicolas',
    'Maria',
    'Luiza',
    'Lorenzo',
    'Lara',
    'Gustavo',
    'Mariana',
    'Felipe',
    'Nicole',
    'Samuel',
    'Rafaela',
    'João Pedro',
    'Heloísa',
    'Daniel',
    'Isadora',
    'Vitor',
    'Lívia',
    'Leonardo',
    'Maria',
    'Clara',
    'Henrique',
    'Ana',
    'Theo',
    'Lorena',
    'Murilo',
    'Gabriela',
    'Eduardo',
    'Yasmin',
    'Pedro',
    'Henrique',
    'Isabelly',
    'Pietro',
    'Sarah',
    'Cauã',
    'Ana Julia',
    'Isaac',
    'Letícia',
    'Caio',
    'Ana Luiza',
    'Vinicius',
    'Melissa',
    'Benjamin',
    'Marina',
    'João',
    'Clara',
    'Lucca',
    'Cecília',
    'João Miguel',
    'Esther',
    'Bryan',
    'Emanuelly',
    'Joaquim',
    'Rebeca',
    'João Vitor',
    'Ana',
    'Beatriz',
    'Thiago',
    'Lavínia',
    'Antônio',
    'Vitória',
    'Davi',
    'Lucas',
    'Bianca',
    'Francisco',
    'Catarina',
    'Enzo',
    'Gabriel',
    'Larissa',
    'Bruno',
    'Maria',
    'Fernanda',
    'Emanuel',
    'Fernanda',
    'João Gabriel',
    'Amanda',
    'Ian',
    'Alícia',
    'Davi',
    'Luiz',
    'Carolina',
    'Rodrigo',
    'Agatha',
    'Otávio',
    'Gabrielly'
]

export const getRandomInt = (arr) => {
    const min = Math.ceil(arr.length / 4);
    const max = Math.floor(arr.length);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const generateNameList = () => {
    const shuffled = [...names].sort(() => 0.5 - Math.random());

    return shuffled.slice(0, 20);
}